var jsText = {
    'text1': 'Añadir al carrito',
    'text2': 'Esperando respuesta',
    'text3': 'Se ha añadido correctamente',
    'text4': 'No disponible',
    'text5': '# uds envío 24h',
    'text6': '¿Le avisamos cuando haya stock?',
    'text7': 'Indique su e-mail',
    'text8': 'Avisar',
    'text9': 'Se está procesando la petición.',
    'text10': 'Esperando respuesta',
    'text11': 'Se ha añadido correctamente al servidor',
    'text12': 'Ya ha enviado una solicitud de información para este producto',
    'text13': 'Pedir cantidades superiores al stock disponible',
    'text14': 'Estimar plazo de entrega para cantidades superiores al stock',
    'text15': 'Cantidad',
    'text16': 'Mínimo # uds.',
    'text17': 'Comentarios',
    'text18': 'Díganos qué necesita y le responderemos en breve.',
    'text19': 'Enviar',
    'text20': 'Ya nos ha solicitado información sobre un stock superior al existente',
    'text21': 'Stock disponible',
    'text22': 'Requerido',
    'text23': 'El formato del correo electrónico no es correcto.',
    'text24': 'La contraseña debe tener 6 caracteres como mínimo.',
    'text25': 'La contraseña no coincide.',
    'text26': 'Sólo se admiten letras, espacios en blanco y guiones.',
    'text27': 'El teléfono sólo admite numeros.',
    'text28': 'El formato del código postal no parece correcto para esta país.',
    'text29': 'El formato de la dirección no parece correcto.',
    'text30': 'La compañía sólo admite números, letras y espacios en blanco.',
    'text31': 'El tamaño mínimo es de %s caracteres.',
    'text32': 'Se está enviando su información. Espere unos instantes.',
    'text33': 'Debe seleccionar al menos una opción.',
    'text34': 'El formato del CIF/NIF no parece correcto.',
    'text35': 'Debe seleccionar una provincia.',
    'text36': 'Debe seleccionar un país.',
    'text37': 'Debe seleccionar un método de envío.',
    'text38': 'Debe seleccionar un método de pago.',
    'text39': 'El importe del pago flexible no puede ser superior al subtotal de los productos.',
    'text40': 'Debe aceptar las condiciones.',
    'text41': 'Se está procesando su petición. Este proceso puede durar varios minutos.',
    'text42': 'Debe seleccionar una dirección de envío o crear una nueva.',
    'text43': 'Dropshipping',
    'text44': 'La cantidad debe ser mayor que 0.',
    'text45': 'El importe debe tener el formato 99 ó 9,99.',
    'text46': 'El formato del código postal es ',
    'text47': 'La cantidad introducida no puede ser mayor que el subtotal de los productos.',
    'text48': 'Debe borrar los productos que estén fuera de stock (marcados en rojo).',
    'text49': 'Ya ha enviado un e-mail para solicitar información sobre esta combinación.',
    'text50': 'El formulario contiene errores.',
    'text51': 'Comentarios para el transportista.',
    'text52': 'Ref. interna',
    'text53': 'Nueva dirección',
    'text54': 'El mensaje contiene caracteres extraños',
    'text55': 'Sólo se admiten imágenes con la extensión gif, jpg, jpeg, png',
    'text56': 'El tamaño máximo del fichero es de %s Kb',
    'text57': 'Una semana',
    'text58': 'Un mes',
    'text59': 'Debe seleccionar una dirección',
    'text60': 'Activar pagos express PayPal',
    'text61': 'importe en €',
    'text62': 'El formato debe ser +NN ó +NNN',
    'text63': 'La contraseña debe contener números y letras mayúsculas y minúsculas. Mínimo 8 caracteres',
    'text64': 'Correo electrónico requerido',
    'text65': 'Debe elegir un idioma',
    'text66': 'Debe elegir al menos un sector',
    'text67': 'Debe elegir al menos un servicio',
    'text68': 'El campo debe ser númerico',
    'text69': 'Próximamente',
    'text70': 'Las cookies recogen información en tu navegador web para ofrecerte una mejor experiencia online.<br>En BigBuy.eu utilizamos cookies, si continuas navegando consideramos que aceptas su uso.',
    'text71': 'Aceptar',
    'text72': 'La dirección no admite comillas dobles. Utilice comillas simples',
    'text73': 'No hay ningún transportista asociado a la dirección de envío facilitada. Por favor, revisela',
    'text74': '¿Está seguro que quiere hacer un bloqueo de stock en este artículo?',
    'text75': 'Este servicio podría ser deshabilitado en función de su ratio de efectividad en las cantidades y artículos bloqueados.',
    'text76': 'Próximas entradas',
    'text77': 'Stock entrega en --DATE-- días  uds',
    'text78': 'Más un recargo de ##PRICE##',
    'text79': 'El email no coincide.',
    'text80': 'Debe seleccionar un plazo de preparación del envío.',
    'text81': 'Este pedido se divide en varios envíos.',
    'text82': 'El plazo de preparación del envío es de %s.',
    'text83': 'Seguimiento de stock'
}